### ISSUE TITLE
May you please release the trained model?

### ISSUE THREAD

**Issue by catalystforyou** [kaist-amsg/LocalTransform#1]
Marvelous work! I love the idea in your paper of defining reaction templates without indicating the specific atom types. Furthermore, I wanna try this method on some other kinds of reactions, and there seems to be no related model file in this repository. Would you mind releasing the trained checkpoints? It will be most helpful for me, and I'd like to thank you in advance.

**Comment by shuan4638** [comment]
Thanks for the kind words!
We didn't share the checkpoints on the GitHub because the size is too large. Instead you may visit the AILab in our group website (https://qchem.kaist.ac.kr/AILAB) to try out the models.
Note that we retrained the model after few modification for faster calculation, so the results may be slightly different from the ones you see on the paper.

**Comment by catalystforyou** [comment]
> Thanks for the kind words! We didn't share the checkpoints on the GitHub because the size is too large. Instead you may visit the AILab in our group website (https://qchem.kaist.ac.kr/AILAB) to try out the models. Note that we retrained the model after few modification for faster calculation, so the results may be slightly different from the ones you see on the paper.

Thank you for your prompt reply, I've noticed you developed an user-friendly webserver for prediction and it's performance is fancy. However, I'm intending to process a batch test on a rather large scale of molecules, it seems that your webserver could only hold one molecule each time. Would it be convenient for you to share your checkpoints via Google Drive, Dropbox or other online tools(it's common to do so when sharing checkpoints on github)?

**Comment by shuan4638** [comment]
Hi @catalystforyou , 
Since GitHub does not allow uploading large file on the repo, we spent some time to reduce the size of LocalTransform model and optimize the performance again. The model is now available at `models/LocalTransform_mix.pth`
Thanks for you patience.

**Comment by catalystforyou** [comment]
Thank you for your update, that means a lot for me.
