### ISSUE TITLE
NameError: name 'products' is not defined

### ISSUE THREAD

**Issue by Agnes-L** [kaist-amsg/LocalTransform#3]
Thank you very much for your guidance few days ago, and very sorry to bother again. The model was trained successfully, but when I run the test file with "python Test.py -sep True", I get this error: "NameError: name 'products' is not defined ". I checked the function that reported the error and found that the parameter 'products' is not defined here. Should I change 'products' to 'reagents' or something else? Thank you so much for your help!
![FQ)JP{(7H BY{U6B7GNF2](https://user-images.githubusercontent.com/64192323/197938443-8adc0551-8838-4e6f-a203-d71906703a46.png)
![IR${VCGW}~YU1VM9R1D4D(A](https://user-images.githubusercontent.com/64192323/197938460-03841e03-0c54-40c0-952e-4a959321eab0.png)

**Comment by shuan4638** [comment]
I also noticed this bug and I fixed it by changing the variables (from `products, reactants` to `reactants, reagents`.
Did you fix it?

**Comment by CesareWang** [comment]
Thank you for your reply! I just noticed after posting this issue that you have already fixed it. So I've followed your method to fix the error. So I closed the issue immediately. Thank you very much for maintaining this outstanding repository! Best wish!
