### ISSUE TITLE
How to train the model with other data

### ISSUE THREAD

**Issue by CesareWang** [kaist-amsg/LocalTransform#4]
Thank you very much for your outstanding work!

The model is well established. But when I am trying to train the model with my own data, I am having a big problem. 

When I run the command "python extract_from_train_data.py", all my input data shows "template problem" (as shown in the picture below). It seems that all my inputs are not being converted into templates during the extraction process. 
![N9M6_ @ET1BC L}XZ)M8A)J](https://user-images.githubusercontent.com/64462870/236985650-a8b2e037-aea6-4ac8-96d9-e08db5c208e2.jpg)

Is this a problem with the format of my input data (my input format is organized as "C1Cc2cccc3cccc1c23.O=O.[H+]>>OC1Cc2cccc3cccc1c23.O")?
![NAI`_LR80IC99A0W4{VWJRG](https://user-images.githubusercontent.com/64462870/236985660-c3107855-346c-4a9f-b2da-6ef813bbcd5f.jpg)

If I want to train the model with my own data, do I have to convert the SMILES code to the format of "[cH:28][cH:29]4)[CH2:16][CH2:17][C:18](=[O:21])[CH2:19][CH2:20]3)[cH:10][cH:11][c:12]2[O:13][CH3:14])[CH2:2][CH2:3][CH2:4][CH2:5]1 24-25;23-25" ? 
![4`N7MXFKS85HHU_SKSSQ5DC_tmb](https://user-images.githubusercontent.com/64462870/236985612-5035c661-0ebf-479e-9cdc-b5a405687864.jpg)

If so, is there any way to convert my data into this format?

I would be very grateful if you could give me some guidance!

**Comment by shuan4638** [comment]
Exactly! The template is derived based on the atom-mapping, the numbers you see on the reactions.
To do this, you can consider using [RXNMapper](https://github.com/rxn4chemistry/rxnmapper), which gives pretty good results to atom-mapping and easy to use!

**Comment by CesareWang** [comment]
Thank you so much! I'll try it right away, thanks for your guidance!
